apiVersion: v1
kind: Secret
metadata:
  name: adguard-secret
  namespace: adguard
  labels:
    app: adguard-home
    app.kubernetes.io/name: adguard
    app.kubernetes.io/instance: adguard
type: Opaque
data:
  users.yaml:CHANGEME #base64 encoded x2
